apiVersion: v1
kind: Service
metadata:
  name: approval-service
  namespace: openaegis
  labels:
    app: approval-service
spec:
  selector:
    app: approval-service
  ports:
    - name: http
      port: 3011
      targetPort: http
