apiVersion: v1
kind: Service
metadata:
  name: kill-switch-service
  namespace: openaegis
  labels:
    app: kill-switch-service
spec:
  selector:
    app: kill-switch-service
  ports:
    - name: http
      port: 3016
      targetPort: http
