apiVersion: v1
kind: Service
metadata:
  name: model-broker
  namespace: openaegis
  labels:
    app: model-broker
spec:
  selector:
    app: model-broker
  ports:
    - name: http
      port: 3008
      targetPort: http
