apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: openaegis
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 3013
      targetPort: http
