apiVersion: v1
kind: Service
metadata:
  name: secrets-broker
  namespace: openaegis
  labels:
    app: secrets-broker
spec:
  selector:
    app: secrets-broker
  ports:
    - name: http
      port: 3014
      targetPort: http
